version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
     - my-net
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/http.d/nginx.conf
      - wp-volume:/var/www/
    restart: always
  
  mariadb:
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - my-net
    volumes:
      - mdb-volume:/var/lib/mysql/
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - my-net
    volumes:
      - wp-volume:/var/www/
    restart: always

volumes:
    wp-volume:
      driver_opts:
        o: bind
        type: none
        device: /home/abuzdin/data/wordpress/
    mdb-volume:
      driver_opts:
        o: bind
        type: none
        device: /home/abuzdin/data/mariadb/

networks:
  my-net:
    driver: bridge
