FROM alpine:3.17
RUN apk update && apk upgrade && apk add --no-cache \
	php8.2 \
	php8.2-fpm \
	php8.2-json \
	php8.2-mysqli \
	php8.2-curl \
	php8.2-dom \
	php8.2-exif \
	php8.2-fileinfo \
	php8.2-hash \
	php8.2-imagick \
	php8.2-mbstring \
	php8.2-openssl \
	php8.2-pcre \
	php8.2-xml \
	php8.2-zip \
	php8.2-opcache \
	wget \
	unzip

EXPOSE 9000
	
